{% set version = "0.1.0a2" %}
{% set setup_py = load_setup_py_data() %}

package:
  name: 'bluesky-browser'
  version: {{ version }}

source:
  git_url: https://github.com/bluesky/bluesky-browser
  git_rev: v{{ version }}
  sha256: 10f7a946ccb18e4870a4dd3fa643f63c5dfd7df3734492f1a47dc2ccdebd21b2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bluesky
    - event-model >=1.9.0a3
    - intake-bluesky >=0.1.0a5
    - jsonschema
    - matplotlib
    - ophyd  # for demo's example data generator -- maybe should be optional?
    - pyqt >=5.8
    - pyzmq
    - qtpy
    - suitcase-jsonl
    - tornado <5  # pinned for bluesky
    - traitlets

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}
